force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description>Annual Clock Process</description>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Evaluation</fullName>
                <default>true</default>
                <label>Evaluation and development of the programme</label>
            </value>
            <value>
                <fullName>Enrolment</fullName>
                <label>Student enrolment</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <label>Planning and implementation of teaching</label>
            </value>
            <value>
                <fullName>Support</fullName>
                <label>Study support and guidance</label>
            </value>
            <value>
                <fullName>Impact</fullName>
                <label>Societal impact and collaboration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Process Description</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Process duration (EndDate-StartDate)</description>
    <formula>EndDate__c - StartDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Process end date</description>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>Process Groups. Users can define their own groups.</description>
    <inlineHelpText>Use existing group or enter new group name.</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Student feedback process</fullName>
            </value>
            <value>
                <fullName>TEE evaluation</fullName>
            </value>
            <value>
                <fullName>Programme review</fullName>
            </value>
            <value>
                <fullName>New programme</fullName>
            </value>
            <value>
                <fullName>Student marketing</fullName>
            </value>
            <value>
                <fullName>Admission process</fullName>
            </value>
            <value>
                <fullName>Student recruitment</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Student engagement</fullName>
            </value>
            <value>
                <fullName>Curriculum design</fullName>
            </value>
            <value>
                <fullName>Student mobility</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Stakeholder collaboration</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Programme level (bachelor, master or both)</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bachelor</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Process start date</description>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test.cls
public with sharing class Test {
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult>getGroups(){
        return [
            SELECT Group__c
            FROM Process__c
            GROUP BY Category__c, Group__c
        ];
    }
   	@AuraEnabled(cacheable=true)
    public static List<Process__c>getGroupProcesses(String GroupName){
        System.debug('Group: ' + GroupName);
        return [
            SELECT Id, Name, Description__c, Category__c, Level__c, StartDate__c, EndDate__c, Duration__c, Link__c
			FROM Process__c
			WHERE Group__c = :GroupName
            ORDER BY StartDate__c, EndDate__c
    	];
    }
}